Added support for prometheus metrics
GoogleCloudPlatform/nginx-docker pull request #50
Opened 2019-03-12 14:53 UTC by harnas-google

2019-03-12 15:05 UTC, harnas-google commented
/gcbrun

2019-03-13 07:54 UTC, axtnsx requested changes
Please, remove binary files (nginx-prometheus-exporter) from repository.

2019-03-13 07:56 UTC, axtnsx commented on templates/docker-entrypoint.sh
> +/usr/local/bin/nginx-prometheus-exporter
nginx should be the main process on the container.

2019-03-13 07:56 UTC, axtnsx commented on 1/debian9/1.15/docker-entrypoint.sh
> +/usr/local/bin/nginx-prometheus-exporter
nginx should be the main process on the container.

2019-03-13 07:57 UTC, axtnsx commented on 1/debian9/1.14/docker-entrypoint.sh
> +/usr/local/bin/nginx-prometheus-exporter
nginx should be the main process on the container.

2019-03-13 16:28 UTC, harnas-google commented
> Please, remove binary files (nginx-prometheus-exporter) from repository.

done

2019-03-13 16:28 UTC, closed without merging