nginx - readme fix
GoogleCloudPlatform/nginx-docker pull request #75
Opened 2021-09-10 10:23 UTC by EugeneKorolevich

2021-09-13 13:29 UTC, ovk6 requested changes

2021-09-13 13:29 UTC, ovk6 commented on README.md
> +Consult [marketplace container documentation](https://cloud.google.com/marketplace/docs/container-images)
Marketplace

2021-09-14 09:27 UTC, EugeneKorolevich commented on README.md
> +Consult [marketplace container documentation](https://cloud.google.com/marketplace/docs/container-images)
done

2021-09-14 11:22 UTC, ovk6 approved these changes

2021-09-14 13:27 UTC, merged